#!/usr/bin/env python

__author__ = "Hans Meine <hans_meine@gmx.net>"

import fig, sys, re, os.path

filename = sys.argv[1]
backgroundColor = fig.CustomColor(None, sys.argv[2])
alpha = float(sys.argv[3])/100

def blend(rgb):
	def blendChannel(fg, bg):
		return int(round(alpha*fg + (1-alpha)*bg))
	return map(blendChannel, rgb, backgroundColor)

infig = fig.File(filename)

for c in infig.colors:
	c.setRGB(*blend(c))

standardMapping = []
for c in fig.standardColors:
	standardMapping.append(None)
standardMapping.append(-1) # map fig.colorDefault to itself

def mapColor(c):
	if c >= fig.colorCustom0:
		return c
	result = standardMapping[c]
	if result == None:
		result = infig.getColor(blend(fig.standardColors[c]))
		standardMapping[c] = result
	return result

for o in infig.allObjects():
	o.penColor = mapColor(o.penColor)
	o.fillColor = mapColor(o.fillColor)

print str(infig),
