#!/usr/bin/env python
import sys, fig
for fn in sys.argv[1:]:
	f = fig.File(fn)
	print "'%s': %s" % (fn, f.landscape and "landscape" or "portrait")
	if f.landscape:
		f.landscape = False
		print "  changed, saving..."
		f.save()
