#!/usr/bin/env python
import fig, sys

if len(sys.argv) < 3:
	print "USAGE: " + sys.argv[0] + " <infile1> <infile2> [outfile]"
	sys.exit(1)

if sys.argv[1] == "-":
	fileA = fig.File(sys.stdin)
	fileB = fig.File(sys.argv[2])
else:
	fileA = fig.File(sys.argv[1])
	if sys.argv[2] == "-":
		fileB = fig.File(sys.stdin)
	else:
		fileB = fig.File(sys.argv[2])

if len(sys.argv) < 4:
	outFile = sys.stdout
else:
	outFile = file(sys.argv[3], "w")

colorMap = {}
for i in range(len(fileB.colors)):
	colorMap[int(fileB.colors[i])] = fileA.getColor(fileB.colors[i].hexCode)

for o in fileB.allObjects():
	if o.penColor >= fig.colorCustom0:
		o.penColor = colorMap[int(o.penColor)]
	if o.fillColor >= fig.colorCustom0:
		o.fillColor = colorMap[int(o.fillColor)]

for o in fileB.objects:
	fileA.append(o)

outFile.write(str(fileA))
